2017-02-24 17:14:47 Error: [Cake\Routing\Exception\MissingControllerException] Controller class View could not be found.
Exception Attributes: array (
  'class' => 'View',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /View
Stack Trace:
#0 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 /var/www/html/cake/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 /var/www/html/cake/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 /var/www/html/cake/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 /var/www/html/cake/webroot/index.php(37): Cake\Http\Server->run()
#13 {main}


2017-02-24 17:23:51 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Connection.php could not be found.
Exception Attributes: array (
  'class' => 'Connection.php',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /connection.php
Stack Trace:
#0 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/ControllerFactory.php(67): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 /var/www/html/cake/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 /var/www/html/cake/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(93): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 /var/www/html/cake/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 /var/www/html/cake/webroot/index.php(38): Cake\Http\Server->run()
#13 {main}


2017-02-24 17:23:59 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Connection could not be found.
Exception Attributes: array (
  'class' => 'Connection',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /connection
Stack Trace:
#0 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 /var/www/html/cake/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 /var/www/html/cake/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 /var/www/html/cake/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 /var/www/html/cake/webroot/index.php(38): Cake\Http\Server->run()
#13 {main}


2017-02-24 17:25:58 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Connection could not be found.
Exception Attributes: array (
  'class' => 'Connection',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /connection
Stack Trace:
#0 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 /var/www/html/cake/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 /var/www/html/cake/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 /var/www/html/cake/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 /var/www/html/cake/webroot/index.php(38): Cake\Http\Server->run()
#13 {main}


2017-02-24 18:48:05 Error: Fatal Error (1): Call to a member function link() on a non-object in [/var/www/html/cake/src/Template/Pages/connection.ctp, line 80]
Request URL: /cake/users
Referer URL: http://localhost/cake/users
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-02-24 18:48:05 Error: [Cake\Error\FatalErrorException] Call to a member function link() on a non-object
Request URL: /cake/users
Referer URL: http://localhost/cake/users
Client IP: 127.0.0.1
Stack Trace:
#0 /var/www/html/cake/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 80)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-02-24 18:54:55 Warning: Warning (4096): Argument 1 passed to Cake\View\Helper\FormHelper::end() must be of the type array, string given, called in /var/www/html/cake/src/Template/Pages/connection.ctp on line 67 and defined in [/var/www/html/cake/vendor/cakephp/cakephp/src/View/Helper/FormHelper.php, line 520]
Request URL: /cake/users
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
Cake\View\Helper\FormHelper::end() - CORE/src/View/Helper/FormHelper.php, line 520
include - APP/Template/Pages/connection.ctp, line 67
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1014
Cake\View\View::_render() - CORE/src/View/View.php, line 973
Cake\View\View::render() - CORE/src/View/View.php, line 597
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
App\Controller\PagesController::display() - APP/Controller/PagesController.php, line 62
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 121
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 95
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 62
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 81
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 90
[main] - ROOT/webroot/index.php, line 38



2017-02-24 18:54:55 Error: Fatal Error (1): Call to a member function link() on a non-object in [/var/www/html/cake/src/Template/Pages/connection.ctp, line 90]
Request URL: /cake/users
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-02-24 18:54:55 Error: [Cake\Error\FatalErrorException] Call to a member function link() on a non-object
Request URL: /cake/users
Client IP: 127.0.0.1
Stack Trace:
#0 /var/www/html/cake/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 90)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-02-24 18:55:11 Warning: Warning (4096): Argument 1 passed to Cake\View\Helper\FormHelper::end() must be of the type array, string given, called in /var/www/html/cake/src/Template/Pages/connection.ctp on line 67 and defined in [/var/www/html/cake/vendor/cakephp/cakephp/src/View/Helper/FormHelper.php, line 520]
Request URL: /cake/users
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
Cake\View\Helper\FormHelper::end() - CORE/src/View/Helper/FormHelper.php, line 520
include - APP/Template/Pages/connection.ctp, line 67
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1014
Cake\View\View::_render() - CORE/src/View/View.php, line 973
Cake\View\View::render() - CORE/src/View/View.php, line 597
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
App\Controller\PagesController::display() - APP/Controller/PagesController.php, line 62
Cake\Controller\Controller::invokeAction() - CORE/src/Controller/Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 121
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 95
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 62
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 81
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 90
[main] - ROOT/webroot/index.php, line 38



2017-02-24 19:14:01 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW) in [/var/www/html/cake/src/Template/Pages/connection.ctp, line 68]
Request URL: /cake/users
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-02-24 19:14:01 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW)
Request URL: /cake/users
Client IP: 127.0.0.1
Stack Trace:
#0 /var/www/html/cake/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', '/var/www/html/c...', 68)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-02-24 20:08:35 Error: Fatal Error (1): Call to a member function find() on a non-object in [/var/www/html/cake/src/Template/Pages/connection.ctp, line 51]
Request URL: /cake/users
Referer URL: http://localhost/cake/users
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-02-24 20:08:35 Error: [Cake\Error\FatalErrorException] Call to a member function find() on a non-object
Request URL: /cake/users
Referer URL: http://localhost/cake/users
Client IP: 127.0.0.1
Stack Trace:
#0 /var/www/html/cake/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 51)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-02-24 20:55:08 Error: [Cake\Routing\Exception\MissingControllerException] Controller class User could not be found.
Exception Attributes: array (
  'class' => 'User',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /user
Referer URL: http://localhost/cake/
Stack Trace:
#0 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 /var/www/html/cake/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 /var/www/html/cake/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 /var/www/html/cake/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 /var/www/html/cake/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 /var/www/html/cake/webroot/index.php(38): Cake\Http\Server->run()
#13 {main}


2017-03-01 19:00:34 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'posicion' cannot be null
Request URL: /users
Referer URL: http://localhost/cake2/users
Stack Trace:
#0 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Statement/StatementDecorator.php(172): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Log/LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Connection.php(276): Cake\Database\Log\LoggingStatement->execute()
#4 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Query.php(190): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 /var/www/html/cake2/src/Template/Pages/connection.ctp(42): Cake\Database\Query->execute()
#6 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(1014): include('/var/www/html/c...')
#7 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(973): Cake\View\View->_evaluate('/var/www/html/c...', Array)
#8 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(597): Cake\View\View->_render('/var/www/html/c...')
#9 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(617): Cake\View\View->render('connection', NULL)
#10 /var/www/html/cake2/src/Controller/PagesController.php(62): Cake\Controller\Controller->render('connection')
#11 [internal function]: App\Controller\PagesController->display('connection')
#12 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(435): call_user_func_array(Array, Array)
#13 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#14 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PagesController))
#15 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#17 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#18 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#19 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#20 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#21 /var/www/html/cake2/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#22 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#23 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#24 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#25 /var/www/html/cake2/webroot/index.php(38): Cake\Http\Server->run()
#26 {main}


2017-03-01 19:02:45 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'posicion' cannot be null
Request URL: /users
Referer URL: http://localhost/cake2/users
Stack Trace:
#0 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Statement/StatementDecorator.php(172): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Log/LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Connection.php(276): Cake\Database\Log\LoggingStatement->execute()
#4 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Query.php(190): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 /var/www/html/cake2/src/Template/Pages/connection.ctp(42): Cake\Database\Query->execute()
#6 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(1014): include('/var/www/html/c...')
#7 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(973): Cake\View\View->_evaluate('/var/www/html/c...', Array)
#8 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(597): Cake\View\View->_render('/var/www/html/c...')
#9 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(617): Cake\View\View->render('connection', NULL)
#10 /var/www/html/cake2/src/Controller/PagesController.php(62): Cake\Controller\Controller->render('connection')
#11 [internal function]: App\Controller\PagesController->display('connection')
#12 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(435): call_user_func_array(Array, Array)
#13 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#14 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PagesController))
#15 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#17 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#18 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#19 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#20 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#21 /var/www/html/cake2/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#22 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#23 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#24 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#25 /var/www/html/cake2/webroot/index.php(38): Cake\Http\Server->run()
#26 {main}


2017-03-01 19:11:44 Error: [RuntimeException] Table "Cake\ORM\Table" is not associated with "validationErrors"
Request URL: /users
Referer URL: http://localhost/cake2/users
Stack Trace:
#0 /var/www/html/cake2/src/Template/Pages/connection.ctp(32): Cake\ORM\Table->__get('validationError...')
#1 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(1014): include('/var/www/html/c...')
#2 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(973): Cake\View\View->_evaluate('/var/www/html/c...', Array)
#3 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(597): Cake\View\View->_render('/var/www/html/c...')
#4 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(617): Cake\View\View->render('connection', NULL)
#5 /var/www/html/cake2/src/Controller/PagesController.php(62): Cake\Controller\Controller->render('connection')
#6 [internal function]: App\Controller\PagesController->display('connection')
#7 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(435): call_user_func_array(Array, Array)
#8 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#9 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PagesController))
#10 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#11 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#14 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#15 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#16 /var/www/html/cake2/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#17 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#18 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#19 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#20 /var/www/html/cake2/webroot/index.php(38): Cake\Http\Server->run()
#21 {main}


2017-03-01 19:13:36 Error: Fatal Error (1): Call to undefined method Cake\ORM\Entity::invalidFields() in [/var/www/html/cake2/src/Template/Pages/connection.ctp, line 33]
Request URL: /cake2/users
Referer URL: http://localhost/cake2/users
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-03-01 19:13:36 Error: [Cake\Error\FatalErrorException] Call to undefined method Cake\ORM\Entity::invalidFields()
Request URL: /cake2/users
Referer URL: http://localhost/cake2/users
Client IP: 127.0.0.1
Stack Trace:
#0 /var/www/html/cake2/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', '/var/www/html/c...', 33)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-03-01 19:15:37 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'posicion' cannot be null
Request URL: /users
Referer URL: http://localhost/cake2/users
Stack Trace:
#0 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Statement/StatementDecorator.php(172): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Log/LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Connection.php(276): Cake\Database\Log\LoggingStatement->execute()
#4 /var/www/html/cake2/vendor/cakephp/cakephp/src/Database/Query.php(190): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 /var/www/html/cake2/src/Template/Pages/connection.ctp(43): Cake\Database\Query->execute()
#6 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(1014): include('/var/www/html/c...')
#7 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(973): Cake\View\View->_evaluate('/var/www/html/c...', Array)
#8 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(597): Cake\View\View->_render('/var/www/html/c...')
#9 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(617): Cake\View\View->render('connection', NULL)
#10 /var/www/html/cake2/src/Controller/PagesController.php(62): Cake\Controller\Controller->render('connection')
#11 [internal function]: App\Controller\PagesController->display('connection')
#12 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(435): call_user_func_array(Array, Array)
#13 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#14 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PagesController))
#15 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#17 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#18 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#19 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#20 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#21 /var/www/html/cake2/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#22 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#23 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#24 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#25 /var/www/html/cake2/webroot/index.php(38): Cake\Http\Server->run()
#26 {main}


2017-03-01 19:24:47 Error: Fatal Error (4): syntax error, unexpected ';', expecting ']' in [/var/www/html/cake2/src/Template/Pages/connection.ctp, line 78]
Request URL: /cake2/users
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-03-01 19:24:47 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ';', expecting ']'
Request URL: /cake2/users
Client IP: 127.0.0.1
Stack Trace:
#0 /var/www/html/cake2/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', '/var/www/html/c...', 78)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-03-01 19:48:02 Error: [BadMethodCallException] Unknown method "updateAll"
Request URL: /users
Referer URL: http://localhost/cake2/users
Stack Trace:
#0 /var/www/html/cake2/vendor/cakephp/cakephp/src/ORM/Query.php(1117): Cake\ORM\Query->_call('updateAll', Array)
#1 /var/www/html/cake2/src/Template/Pages/connection.ctp(37): Cake\ORM\Query->__call('updateAll', Array)
#2 /var/www/html/cake2/src/Template/Pages/connection.ctp(37): Cake\ORM\Query->updateAll(Array, Array)
#3 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(1014): include('/var/www/html/c...')
#4 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(973): Cake\View\View->_evaluate('/var/www/html/c...', Array)
#5 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(597): Cake\View\View->_render('/var/www/html/c...')
#6 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(617): Cake\View\View->render('connection', NULL)
#7 /var/www/html/cake2/src/Controller/PagesController.php(62): Cake\Controller\Controller->render('connection')
#8 [internal function]: App\Controller\PagesController->display('connection')
#9 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(435): call_user_func_array(Array, Array)
#10 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#11 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PagesController))
#12 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#14 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#15 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#16 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#17 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#18 /var/www/html/cake2/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#19 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#20 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#21 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#22 /var/www/html/cake2/webroot/index.php(38): Cake\Http\Server->run()
#23 {main}


2017-03-01 19:48:27 Error: [BadMethodCallException] Unknown method "updateAll"
Request URL: /users
Referer URL: http://localhost/cake2/users
Stack Trace:
#0 /var/www/html/cake2/vendor/cakephp/cakephp/src/ORM/Query.php(1117): Cake\ORM\Query->_call('updateAll', Array)
#1 /var/www/html/cake2/src/Template/Pages/connection.ctp(37): Cake\ORM\Query->__call('updateAll', Array)
#2 /var/www/html/cake2/src/Template/Pages/connection.ctp(37): Cake\ORM\Query->updateAll(Array, Array)
#3 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(1014): include('/var/www/html/c...')
#4 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(973): Cake\View\View->_evaluate('/var/www/html/c...', Array)
#5 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(597): Cake\View\View->_render('/var/www/html/c...')
#6 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(617): Cake\View\View->render('connection', NULL)
#7 /var/www/html/cake2/src/Controller/PagesController.php(62): Cake\Controller\Controller->render('connection')
#8 [internal function]: App\Controller\PagesController->display('connection')
#9 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(435): call_user_func_array(Array, Array)
#10 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#11 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PagesController))
#12 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#14 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#15 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#16 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#17 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#18 /var/www/html/cake2/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#19 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#20 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#21 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#22 /var/www/html/cake2/webroot/index.php(38): Cake\Http\Server->run()
#23 {main}


2017-03-01 19:48:43 Error: [BadMethodCallException] Unknown method "updateAll"
Request URL: /users
Referer URL: http://localhost/cake2/users
Stack Trace:
#0 /var/www/html/cake2/vendor/cakephp/cakephp/src/ORM/Query.php(1117): Cake\ORM\Query->_call('updateAll', Array)
#1 /var/www/html/cake2/src/Template/Pages/connection.ctp(37): Cake\ORM\Query->__call('updateAll', Array)
#2 /var/www/html/cake2/src/Template/Pages/connection.ctp(37): Cake\ORM\Query->updateAll(Array, Array)
#3 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(1014): include('/var/www/html/c...')
#4 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(973): Cake\View\View->_evaluate('/var/www/html/c...', Array)
#5 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(597): Cake\View\View->_render('/var/www/html/c...')
#6 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(617): Cake\View\View->render('connection', NULL)
#7 /var/www/html/cake2/src/Controller/PagesController.php(62): Cake\Controller\Controller->render('connection')
#8 [internal function]: App\Controller\PagesController->display('connection')
#9 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(435): call_user_func_array(Array, Array)
#10 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#11 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PagesController))
#12 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#14 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#15 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#16 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#17 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#18 /var/www/html/cake2/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#19 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#20 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#21 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#22 /var/www/html/cake2/webroot/index.php(38): Cake\Http\Server->run()
#23 {main}


2017-03-01 19:53:51 Error: [BadMethodCallException] Unknown method "save"
Request URL: /users
Referer URL: http://localhost/cake2/users
Stack Trace:
#0 /var/www/html/cake2/vendor/cakephp/cakephp/src/ORM/Query.php(1117): Cake\ORM\Query->_call('save', Array)
#1 /var/www/html/cake2/src/Template/Pages/connection.ctp(34): Cake\ORM\Query->__call('save', Array)
#2 /var/www/html/cake2/src/Template/Pages/connection.ctp(34): Cake\ORM\Query->save()
#3 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(1014): include('/var/www/html/c...')
#4 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(973): Cake\View\View->_evaluate('/var/www/html/c...', Array)
#5 /var/www/html/cake2/vendor/cakephp/cakephp/src/View/View.php(597): Cake\View\View->_render('/var/www/html/c...')
#6 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(617): Cake\View\View->render('connection', NULL)
#7 /var/www/html/cake2/src/Controller/PagesController.php(62): Cake\Controller\Controller->render('connection')
#8 [internal function]: App\Controller\PagesController->display('connection')
#9 /var/www/html/cake2/vendor/cakephp/cakephp/src/Controller/Controller.php(435): call_user_func_array(Array, Array)
#10 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#11 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PagesController))
#12 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#14 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#15 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#16 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#17 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#18 /var/www/html/cake2/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#19 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#20 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#21 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#22 /var/www/html/cake2/webroot/index.php(38): Cake\Http\Server->run()
#23 {main}


2017-03-01 19:56:17 Error: Fatal Error (1): Call to a member function update() on a non-object in [/var/www/html/cake2/src/Template/Pages/connection.ctp, line 18]
Request URL: /cake2/users
Referer URL: http://localhost/cake2/users
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-03-01 19:56:17 Error: [Cake\Error\FatalErrorException] Call to a member function update() on a non-object
Request URL: /cake2/users
Referer URL: http://localhost/cake2/users
Client IP: 127.0.0.1
Stack Trace:
#0 /var/www/html/cake2/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-03-02 00:46:35 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Turbinas could not be found.
Exception Attributes: array (
  'class' => 'Turbinas',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /turbinas
Stack Trace:
#0 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 /var/www/html/cake2/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 /var/www/html/cake2/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 /var/www/html/cake2/vendor/cakephp/cakephp/src/Http/Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 /var/www/html/cake2/webroot/index.php(38): Cake\Http\Server->run()
#13 {main}


